# Generated by Django 5.1.7 on 2025-06-30 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_email_alter_user_passage_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title or name of the trip (e.g., "Vacation in Paris").', max_length=100, verbose_name='title')),
                ('location', models.CharField(help_text='Destination of the trip (e.g., "Paris, France").', max_length=100, verbose_name='location')),
                ('trip_date', models.DateField(help_text='Date when the trip took place.', verbose_name='trip date')),
                ('description', models.TextField(blank=True, help_text='Additional details or notes about the trip.', null=True, verbose_name='description')),
                ('photo', models.ImageField(blank=True, help_text='Photo related to the trip uploaded by the user.', null=True, upload_to='trips/', verbose_name='photo')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the trip entry was created.', verbose_name='created at')),
                ('user', models.ForeignKey(help_text='Reference to the user who owns the trip.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Trip',
                'verbose_name_plural': 'Trips',
                'ordering': ['-created_at'],
            },
        ),
    ]
