# Generated by Django 5.1.7 on 2025-07-01 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_trip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='passage_id',
        ),
    ]
