# Generated by Django 5.1.7 on 2025-07-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_user_passage_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='photo',
            field=models.TextField(blank=True, help_text='Photo related to the trip uploaded by the user.', null=True, verbose_name='photo'),
        ),
    ]
